language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pytest-cov
  - pip install codecov
script:
  - python -m pytest --cov=scitime
  - python -m flake8
after_success:
  - codecov