name: test-and-publish
on:
  push:
    branches:
      - cc_3_12

# todo [CC]: manage latest mac and windows os tests
jobs:
  openergy:
    uses: openergy/ogithub-actions/.github/workflows/opypackage-standard-v05.yml@cc_opyplus
    with:
      install-eplus-2210: true
      os-requirements: ["ubuntu-latest", "windows-latest"]

    secrets:
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      AZURE_CONDA_CHANNEL_KEY: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
      CONDA_CHANNEL_SYSADMIN_URL: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}
      PYPI_OPENERGY_PASSWORD: ${{ secrets.PYPI_OPENERGY_PASSWORD }}
